### PR TITLE
Clarifies deployment documentation

### PR DESCRIPTION
**Pull request by djperrefort**
This PR separates the deployment and installation documentation into distinct sections. Various edits are also made for clarity.

### CODE REVIEW

**Comment by djperrefort** [comment]
It looks like this is failing because we deleted the testing resources in GCP.

**Comment by troyraen** [comment]
This can be fixed by running `auto_setup()` from `broker.gcp_setup` (Documenting offline conversation)

**Comment by troyraen** [comment]
I also think the `deployment/overview.rst` page should actually list the steps one needs to take to deploy the broker along with links to where (in our documentation) the detailed instructions are. We can come back to this after we redeploy it ourselves.

**Comment by djperrefort** [comment]
As a note to self, I should add to the documentation that most of the docker tasks require `sudo`.

**Pull request merged**
