### PR TITLE
Changes for elasticc

### PR DESCRIPTION
**Pull request by hernandezc1**
Partially addresses #107 

- created a new directory: broker/cloud_run/elasticc (and added the broker classification schema)
- updated SuperNNova & Extragalactic Transient Filter modules
- updated setup_broker.sh script
- added SuperNNova BigQuery table (schemas included in broker/setup_broker/templates)

### CODE REVIEW

**Review by troyraen — COMMENTED** [review]
Here are deployment and testing instructions. Step 3 can be done before 1 and 2.

0. Activate your conda environment and update broker utils: `pip install --upgrade pgb-broker-utils`. Also make sure you have pulled down all changes to the branch you're working in: in the root directory, do `git fetch` then `git pull`.

1. Work through the [Download Alerts](https://pitt-broker.readthedocs.io/en/develop/broker/alerts-for-testing.html#download-alerts) section of the Alerts for Testing page. It will have you download the elasticc alerts to a particular directory (partially of your choosing), and it will store the directory path as an environment variable so that the alerts are easy to access in the future. You might as well download the ZTF alerts too so that you're setup to use them.

2. Work through the first two subsections of [Load alerts and test](https://pitt-broker.readthedocs.io/en/develop/broker/alerts-for-testing.html#load-alerts-and-test) ("Setup" and "Load an alert as a dictionary for local testing") on that same page. Use the following setup options:
- Publish the elasticc test alerts to the topic `SuperNNova` (name stub).
- Use `mock = ["SuperNNova"]` to generate mock classifier results for your module to use.
- Pull from the subscription `classifications`.

3. Deploy the module and setup related cloud resources (code below). Just test the module you worked on (publish_classifications) the first time you run thru this. You can comment out the filter and classifier Cloud Functions from the setup script.
To do some sanity checks and make sure the setup script completed properly you can look at the resources in the web console. See the [View and Access Resources](https://pitt-broker.readthedocs.io/en/develop/broker/run-a-broker-instance/view-resources.html) page for some links and pointers on where to look.

Run the setup script (command line):

```
# activate your conda environment 
# make sure you're in the root directory of this repo/branch on your local machine

export TESTID='ch'
export SURVEY='elasticc'

cd broker/broker_setup
./deploy_elasticc_test.sh "${TESTID}" "${SURVEY}"
```

If you need to make changes to the module, do so, and then run the setup script again to redeploy it. (You can ignore the errors saying that some resources already exist.)
If you want to start over with a clean broker instance, skip to the bottom of this comment and use the code to delete all the resources, then run the setup again.

4. Test the module by pushing a single alert through and then looking at the message your module publishes; follow the instructions in [Publish a single alert, then pull from a subscription and check the message](https://pitt-broker.readthedocs.io/en/develop/broker/alerts-for-testing.html#publish-a-single-alert-then-pull-from-a-subscription-and-check-the-message). 

5. Test the module by pushing a batch of alerts through and validate that your module published messages for all of them; follow the instructions in [Publish a batch of alerts, then pull from a subscription and validate the message ids](https://pitt-broker.readthedocs.io/en/develop/broker/alerts-for-testing.html#publish-a-batch-of-alerts-then-pull-from-a-subscription-and-validate-the-message-ids).
 Check whether your module produced the expected Pub/Sub stream by following the instructions in the section [Pull alerts from a Pub/Sub subscription](https://pitt-broker.readthedocs.io/en/develop/broker/alerts-for-testing.html#pull-alerts-from-a-pub-sub-subscription).

6. When you are completely done, run the setup script again with `teardown=True` to delete all the resources associated with your broker instance:

```
teardown=True
./deploy_elasticc_test.sh "${TESTID}" "${SURVEY}" "${teardown}"
```

**Comment by hernandezc1** [comment]
Partially addresses #107

**Comment by troyraen** [comment]
@hernandezc1 to deploy the end-to-end broker, follow the instructions on our docs page [Setup the Broker](https://pitt-broker.readthedocs.io/en/latest/broker/run-a-broker-instance/setup-broker.html). For now, you only need the section called Setup the Broker Instance. (Note that you don't need to clone the repo again, just make sure you have `cd`d into the setup_broker directory.

You should start from scratch, so either use a different testid than before or delete the resources you setup earlier by following the teardown instructions above.

You'll want to validate the output in all of the Pub/Sub topics that are published by the last modules in the pipelines. This includes:
- classifications
- alert_avros
- BigQuery

To do this, you need to create subscriptions to the topics. You can do this from the command line with (change `mysubscription` and `mytopic` to appropiate values):
```bash
SUBSCRIPTION="mysubscription"
TOPIC="mytopic"
gcloud pubsub subscriptions create "$SUBSCRIPTION" --topic="$TOPIC"
```

Follow the same instructions as you did before (above) to run test alerts through, with these changes:
- Publish the elasticc test alerts to the alerts topic.
- Set `mock = None`
- In the last step where you pull from a subscription and validate message IDs, do this for every subscription that you created above.

**Comment by troyraen** [comment]
@hernandezc1 Thank you for creating the `elasticc/main` branch. After we hung up, I realized that we should base that new branch on `develop` (not on `u/CH/test` as I originally asked for and you did). So I've done that now. And the reason is: now we can complete this particular PR in a simple and clean way, which will then free us up to continue on with ELAsTiCC development -- this is a big enough project that we should do it as a whole series of small-ish PRs. What you have right now in this PR is the first logical chunk of the project, and I'd like to call it complete. 

Specifically, here's where we go from here:

- (...see the section "Plan for the immediate future" in #164)

**Comment by troyraen** [comment]
> After we hung up, I realized that we should base that new branch on `develop`

I also realized that our repo does _not_ have a branch called `main`...

So, I'm changing the new branch name from `elasticc/main` to `main/elasticc`. This has the advantage that it introduces an easier naming schema, if we want to continue keeping separate main branches for codes that run different surveys... so a future `main/ztf` and/or `main/lsst` would all sit next to each other alphabetically, and would be easily understood as the main branches for those surveys.

...I wanted `main/elasticc` to begin with, but newer repos already have a branch called `main` and thus cannot have one called `main/<anything>`.

**Review by troyraen — APPROVED** [review]

**Pull request merged**
