### PR TITLE
v/tjr/0.3.1

### PR DESCRIPTION
**Pull request by troyraen**
Reference links:
- [Dashboard for the `v031` testing instance](https://console.cloud.google.com/monitoring/dashboards/builder/broker-instance-v031?project=ardent-cycling-243415&dashboardBuilderState=%257B%2522editModeEnabled%2522:false%257D&startTime=20210412T052643-04:00&endTime=20210412T073043-04:00) (the link will send you directly to the time period of the ~1 hour-long test I ran this morning)
- To find individual resources, see [Where to view your resources
](https://github.com/mwvgroup/Pitt-Google-Broker/blob/v/tjr/0.3.1/broker/README.md#where-to-view-your-resources)
- [Setup and testing notebook](https://github.com/mwvgroup/Pitt-Google-Broker/blob/v/tjr/0.3.1/v0.3.1/setup_test_v031.ipynb)

Updates included in v0.3.1 (to be checked off after final testing):
- [x] adds a Monitoring Dashboard for broker testing instances
- [x] adds pipeline filter `is_pure(alert)` and related Pub/Sub stream `ztf_alerts_pure`
- [x] adds pipeline sink to the new `ztf_alerts.DIASource` BigQuery table
- [x] adds the alert data to the `ztf_salt2` Pub/Sub stream
- [x] renames the Pub/Sub stream `ztf_alert_data` -> `ztf_alerts`
- [x] renames`ztf_alert_avro_bucket` -> `ztf_alert_avros` (storage bucket and Pub/Sub topic)
- [x] changes the format of the Avro file names `{ztftopic}_{timestamp}.avro` -> `{objectId}.{candid}.{ztftopic}.avro`
- [x] adds BigQuery table schema json files and updates `setup_gcp.py` to create the tables from them

### CODE REVIEW

**Comment by troyraen** [comment]
@wmwv just a heads up that I'll be requesting your review on this soon. It already includes all the changes I intend, I'm just testing and debugging. I'll give you a notebook with the results. Hoping to merge both this and the tutorial PR to master by the beginning of next week.

**Comment by troyraen** [comment]
@wmwv I think this is all working now and ready for your review. Use the first comment on this PR as your entry point. The Dashboard (link in comment) may be helpful. You probably do not need to look at the setup and testing notebook. If you want to track down a particular resource, see [Where to view your resources](https://github.com/mwvgroup/Pitt-Google-Broker/blob/v/tjr/0.3.1/broker/README.md#where-to-view-your-resources).

After my office hours today, I will: 
- do a more detailed check 
- reprocess all the Avro files we have in storage through both of the Beam pipelines, replacing existing BQ tables, and adding the new ones. I will also rename the Avro files in the process so they can be accessed with the new naming scheme.
- make an attempt at connecting to/setting us up for the DECam stream.

**Comment by troyraen** [comment]
@cmazzdaher @djperrefort Tagging you here for an FYI. You do not need to actually review this PR, but you may want to read the 1st comment on the PR to see what the changes are.

**Review by wmwv — APPROVED** [review]
LGTM

Great work!

A few places you say "I am" or "in my experience".  Obviously to you and me, you, Troy Raen, wrote all of this stuff.  But to an outside reader of the documentation, they don't have that in their mind.  So just note such sentences with a "I (Troy Raen) am" or "Troy Raen: In my experience".  I think they're good.  They serve a good role of saying "here's how I do something but I'm not claiming it's The Way" or "here's what I've experienced, I don't really fully understand why."

**Pull request merged**
