### PR TITLE
Add unittesting workflow

### LINKED ISSUE #73: Disable checking of PRs that always fails.
I believe the current status is that the automatic test that GitHub runs for a PR always fails.  Let's disable that check until we figure out how to change things so that we expect it to succeed.  I'd like to not get into the a bit of expecting the test to fail and ignoring red X marks.

### PR DESCRIPTION
**Pull request by djperrefort**
Relevant to Issues #81 and #82
Closes #73 

- Removes tests for code that doesn't exist anymore
- Adds a github actions workflow for running unittests
- Adds an example unit test (just so the workflow has something to run)
- Deletes travis config file

### CODE REVIEW

**Comment by djperrefort** [comment]
@troyraen It looks like there is a dependency issue with the requirements file. I get a similar error when building locally. Are you able to install the broker package in a clean environment?

**Comment by troyraen** [comment]
> I never need to install this all in the same place

Ok, yes, I do have it all installed locally (i.e., in the same place) and I test all the pieces locally. But my point is

> the end-to-end broker will not run from a single machine.

So I've never had a need to install the entire broker "package" together in a clean environment. I install each piece component in the specific clean environment in which it is designed to run.

**Comment by djperrefort** [comment]
The problem is coming from the requirements file in root. The call to `pip install -r requirements.txt` fails with one of two error messages. In Python 3.7 I get the following during the installation of `google-auth`

> INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking

In Python 3.8 and 3.9 I get 

> ERROR: Could not find a version that satisfies the requirement astropy==3.2.1

**Comment by troyraen** [comment]
> The problem is coming from the requirements file in root. 

Documenting our offline discussion, try using the file at broker/broker_utils/requirements.txt. The requirements file in root is incomplete and not intended for this use case. I am sorry it's even there to begin with, since its very existence implies that you should be able to use it in the way you are trying to use it. This will get cleaned up as part of #79.

> In Python 3.8 and 3.9 I get
> 
> > ERROR: Could not find a version that satisfies the requirement astropy==3.2.1

I think we need to stick to Python 3.7. You are the 3rd person to report trouble when trying to install a broker component in something other than Python 3.7. For example, Issue #76 is related.

**Pull request closed without merging**
