### PR TITLE
Pub/Sub Module

### PR DESCRIPTION
**Pull request by cnmazz**
Troy: Since Daniel's not here and may not be responsive, can you take a quick look over this?

Adds a module for publishing and accessing messages via Pub/Sub. Publishing and subscribing are implemented as separate functions in message_service.py, each requiring a GCP project ID to run. Both functions assume the alert structure from alert_acquisition.ztf.get_alerts() and may not work properly with other forms of message data.

### CODE REVIEW

**Comment by troyraen** [comment]
Yes, I can look at it. Do you actually need me to test the new functions?
If so, I can try, but I've had to uninstall some things and I'm not sure
the Pitt broker is going to run on my machine without some effort, so I'm
not sure how soon I can do that.

- Troy

On Mon, Jun 17, 2019 at 5:16 PM cnmazz <notifications@github.com> wrote:

> @cnmazz
> <https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcnmazz&data=02%7C01%7Ctroy.raen%40pitt.edu%7C0e030632a0c54512e13e08d6f3690ca7%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C636964029854037532&sdata=rNPU5zXan1E8vaNGJIDnC4HWxD3EsObRULkzWtKXNkI%3D&reserved=0>
> requested your review on: #14
> <https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmwvgroup%2FPitt-Google-Broker%2Fpull%2F14&data=02%7C01%7Ctroy.raen%40pitt.edu%7C0e030632a0c54512e13e08d6f3690ca7%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C636964029854047527&sdata=p5ZS7QTuzJeiDWe%2BESXX99CSsNqlraDtwK5L8pX8sLM%3D&reserved=0>
> Pub/Sub Module.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmwvgroup%2FPitt-Google-Broker%2Fpull%2F14%3Femail_source%3Dnotifications%26email_token%3DAHBNXRZQDOXKX2ZSROPIH4LP275KNA5CNFSM4HY2KPW2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOSAW4ZKA%23event-2418920616&data=02%7C01%7Ctroy.raen%40pitt.edu%7C0e030632a0c54512e13e08d6f3690ca7%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C636964029854047527&sdata=%2FItQ4SNX0K5a0kJouWkAeUTQaQsJALDcL0C8ndaOddk%3D&reserved=0>,
> or mute the thread
> <https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHBNXR33G53ZAF4PCSBKLU3P275KNANCNFSM4HY2KPWQ&data=02%7C01%7Ctroy.raen%40pitt.edu%7C0e030632a0c54512e13e08d6f3690ca7%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C636964029854057523&sdata=7pUAardJXI2es%2ByXIZgpdUc0%2B00bVSCDQK4q7tLy718%3D&reserved=0>
> .
>
-- 
- Troy Raen

**Comment by troyraen** [comment]
Ok, I have Pitt-Broker running on my machine. I have a couple of questions before I test those functions (not exactly sure how I need to pass the arguments). Can we chat tomorrow morning?

**Comment by troyraen** [comment]
In pubsub_tutorial.md:
- At least most of the steps in the '## Initial Setup' section should have been completed when first installing the Pitt Broker package. There are already some instructions here: https://pitt-broker.readthedocs.io/en/latest/installation.html, though what you have in this md file is more detailed. We should consider merging this section with the installation instructions.
- In the section '### Starting a Topic', I had to enable the API before I could create a topic. This may be because I didn't do it in the initial setup when I created my credentials. If so, we should add specific instructions to the install instructions (see previous bullet point).
- I was unable to use the command `gcloud pubsub topics create my_topic` (received error `bash: gcloud: command not found`. Is there a dependency that needs to be installed?
- In the section '#### Publishing', I am unable to do `from google.cloud import pubsub_v1`; I get the error `cannot import name 'pubsub_v1' from 'google.cloud'`. Again, I suspect I don't have the correct dependencies installed.

I was unable to get any further. As far as I can tell the requirements.txt file hasn't been updated since I reinstalled the Pitt Broker software last week, but it seems like I don't have the correct dependencies installed. Very well could be my mistake/misunderstanding, but I need some clarification.

**Comment by cnmazz** [comment]
Thanks for taking a look!

- There probably are some redundancies between '## Initial Setup' and Daniel's documentation. I just wrote down everything that I did in roughly the order I did it (albeit, there was some minor cursing and sighs as I figured this all out by some inadequate tutorials and painful trial/error). This file was intended for someone who wanted to do this independently of the state of our broker's official docs, which I think is important, seeing as this file is more for us developers.
- I go over enabling the API in the '## Initial Setup' section, so you should've done this before getting to making a topic. If that wasn't clear, I can make this more obvious. Also, you have to enable each of the APIs you want, so this is something that may not be fully up to date in just Daniel's documentation, hence why I hesitate to trim my docs until they get smoothly merged.
- I believe you have to install the gcloud command-line tools if you want to use those forms of the commands on your computer; otherwise, you'd use these commands on your online GCP page, which includes the gcloud terminal.  You bring up a good point that I had not clarified this in the md instructions, so I should make this more clear. Personally, I'd rather stick to making topics and subscriptions via the GUI and then writing python code to do the rest rather than have to learn the gcloud terminal, but I should leave that decision to the user.
- Yes, you have to specifically install pubs_v1, which I believe was a pip install. I didn't mention this anywhere, and I definitely should have. I will fix this.

Thanks for the feedback! Hopefully, I can clarify things enough that you can get it running. Once you get all the dependancies installed and APIs/rights enabled, the actual python code is very easy. It's just everything else to get to this point that was unclear in the online tutorials. I'd be curious to hear from Ross and get an expert's introduction as opposed to my fumbling.

**Comment by troyraen** [comment]
I think it makes sense to leave the tutorial file separate from the installation instructions. But I think we'll want to update the installation instructions to include anything that's needed in the initial setup for Pub/Sub (e.g. enabling the API). Then we can direct people to skip the initial setup section if they've already done the install and that way they don't have to figure out which parts they've done already and which parts they still need to do.

The gcloud command-line tools and pubs_v1 should be added to the requirements.txt file.

I might not get to it until next week, but I'll install those dependencies and see if everything works. Then I can update the things I mentioned above.

**Comment by cnmazz** [comment]
Agreed on all counts. I'll make the suggested changes as soon as I have a chance, but that might also not be until next week.

**Comment by troyraen** [comment]
Christine,

After downloading the dependencies and fixing my permissions I was able to publish and subscribe to a topic, so it looks to me like this is working. I used the GUI rather than the GCP console commands, so I haven't tested those commands.

**Comment by wmwv** [comment]
@troyraen Do you approve of this PR?  If so, could you formally indicate this?

**Comment by troyraen** [comment]
@djperrefort I tried to test this by sending local alerts, but found that I could no longer retrieve them. I think this may be related to the change you were making in what the get_local_alerts() function returns. 
Screen Shot 2019-07-26 at 5 01 11 PM

**Comment by troyraen** [comment]
Ok, I was able to get the alerts in raw format from the ztf_archive module, publish them, and subscribe/receive them. So I think this is good to go.

**Pull request merged**
