### PR TITLE
Drop Dataflow jobs

### PR DESCRIPTION
**Pull request by troyraen**
Here is my proposal for dropping the Dataflow jobs and rebuilding some affected pieces. I've chunked the steps into several PRs.

@wmwv requesting a ~design review of the plan~ review of this high-level implementation plan.

@cmazzdaher @djperrefort input welcome.

### This PR

**Step 1**: Remove the Dataflow jobs from the nightly routine

- [x] comment the jobs out of `night-conductor`'s scripts
- [x] update docs

### Existing PRs (done)

**Step 2**: Replace the modules (flagging #96)

- [x] BigQuery storage -> #93 
- [x] Extragalactic transients filter and Salt2 fit -> #71 (Salt2 gets replaced by SuperNNova)
- [x] Purity filter: ~#(TBD). I have thoughts about how to structure the writing and deployment of filters as Cloud Functions... too tired to open another PR at the moment.~ -> #112 

### Next PR (submitted #111)

**Step 3**: Delete all the `beam` files:

- `broker/beam/*`
- `broker/broker_utils/broker_utils/beam_transforms.py`
- `broker/night_conductor/start_night/start_beam_jobs.sh`
- `broker/night_conductor/start_night/drain_beam_jobs.sh`

**Step 4**: Update these files to accommodate the deleted files:

- remove `beam` module from `broker/broker_utils/broker_utils/\__init__.py`
- remove Dataflow job from `broker/night_conductor/start_night/start_night.sh`
- remove Dataflow job from `broker/night_conductor/end_night/end_night.sh`
- remove `beam` dir from `broker/setup_broker/upload_broker_bucket.sh`

**Step 5**: Remove Salt2 resources

- remove BigQuery and Pub/Sub resource names from `broker/setup_broker/setup_gcp.py`
- delete `broker/setup_broker/templates/bq_ztf_salt2_schema.json`
- delete `broker/setup_broker/templates/bq_decat_salt2_schema.json`
- ~update `broker/setup_broker/templates/dashboard.json`~ this dashboard needs a larger makeover

Goodbye Salt2, thanks for your help.

### PR after that (#113)

**Step 6**: Update `broker_utils` requirements

- drop `apache-beam`
- unpin `google-cloud-bigquery`. I think this should not require any refactoring.
- test `gcp_utils` functions that use `bigquery`: `insert_rows_bigquery()`, `load_dataframe_bigquery()`, `query_bigquery()`. Write unit tests.
- unpin `numpy`
- test `data_utils` function that uses `numpy`: `mag_to_flux()`. Write unit test.
- unpin `google-cloud-pubsub`. This will bump it from version `1.x` to `2.x`.
- refactor `gcp_utils` functions that use `pubsub`: `publish_pubsub()`, `pull_pubsub()`, `streamingPull_pubsub()`. This should be simple (just send all `request`s as `dict`s).
- ~refactor `consumer_sim` functions that use `pubsub`~ put this task into #74.
- test functions that use `pubsub`. Write unit tests.

### Anytime PR

**Step 7**: ~Update `night-conductor` requirements.~ The night conductor VM now has a lot less to do. Proposing #95 instead.

This does not have to wait for previous steps.

### CODE REVIEW

**Comment by wmwv** [comment]
As a minor bit of semantics, I read the above as a high-level Implementation plan rather than a Design plan.  The Design would be the part that describes how alerts go through the system in the new paradigm and how that system is structured.

**Comment by wmwv** [comment]
I think you should keep SALT2 as a thing you can run.  In general,  we will want to be able to run various classifiers/fitters, SALT2 is one of them, SuperNNova, Upsilon, etc.  These are all just functions that take as input the alert data and produce a classification, score, fit parameters as outputs.  They should structurally fit in in the same way in the pipeline.

If what you're saying is that you should remove the Dataflow job that runs SALT2, then of course, yes.  But we will want to be able to run SALT2 on the input data.

**Comment by wmwv** [comment]
I would merge IOR close the existing PRs that are hanging around first.  Perhaps you already have a mapping in your brain about how all of the work would flow out of those PRs into new things, but from a simplistic organizational point of view I think it's best to close IOR merge PRs clearly and then start new ones.  Otherwise it becomes really hard to remember that while the core functionality of a given branch is still what you want in a different branch, there's some silly little configuration format change that makes things incompatible, etc.

[IOR: Inclusive OR]

**Review by wmwv — COMMENTED** [review]
Thoughts given in main comments.  In brief
* Plan to keep SALT2 as a thing we can run.  If it can't run as a cloud function, OK.  File an issue against that.
* Merge existing PRs now and then start the additional branches for this work.

**Comment by wmwv** [comment]
I specifically mean merge IOR close #71, #72, and #90.

**Comment by troyraen** [comment]
> I think you should keep SALT2 as a thing you can run.

I see. The code just needs to be pulled out of the `apache_beam` wrappers and structured in the way Cloud Functions require. Opened #98.

**Comment by troyraen** [comment]
> I would merge IOR close the existing PRs that are hanging around first. Perhaps you already have a mapping in your brain about how all of the work would flow out of those PRs into new things, but from a simplistic organizational point of view I think it's best to close IOR merge PRs clearly and then start new ones.

I can switch steps 1 and 2, and also be more clear about what my actual plan was. I was trying not to make everyone else think about how I was going to merge all these PRs, but I see now that I just made it more confusing. 

My plan was to merge #71, #72, #90, and #93 in order, into the `develop` branch  and make sure everything works together before merging with `master`.

I will add this PR (#94) to the *back* of that line.

@wmwv does that address these concerns? (I think it does, per our offline discussion.)

A wrinkle:
The current `develop` branch has diverged from the rest of the relevant branches due to #86. I would like to resolve all the conflicts once, rather than individually for each PR. Therefore, I'd like to merge this line of PRs into the branch `develop_beam_cloudfncs` first, and then merge into `develop` and then `master`.

Is it ok to request that the branch in this PR (`tjr/drop_beam') be merged into `develop_beam_cloudfncs`? Or should I rebase and request to merge into the branch that is actually at the back of the line?

**Comment by troyraen** [comment]
@wmwv Will you give a final review/approval for this so I can merge it in? Everything in the main comment above has either been completed or moved to an issue.

**Comment by troyraen** [comment]
@wmwv To be more specific, I am asking for a stamp of approval to push through the actual code changes in this PR. I am corralling this whole group of PRs into `develop`, where I will make sure everything works together, and write an actual test (details TBD). 

Feel free to comment on anything in the main comment (etc). I realize now that all of that really should have been an Issue instead.

**Comment by troyraen** [comment]
@wmwv Looks like you're off the hook for this one. I accidentally included these code changes in #111 also. @djperrefort reviewed/approved #111 this morning, and I merged it in. Because it included these commits, this PR was automatically marked "merged" and closed.

**Pull request merged**
